### ISSUE TITLE
Issue while running layered_planner.py

### ISSUE THREAD

**Issue by Scientist786** [RuslanAgishev/adaptive_swarm#2]
Hello
I have been searching in pip for swarmlib package as included in requirements.txt but I cannot find one. I tried pip3 to search the package and it was successfully installed but it does not contain Drone function. I get this error while running it.

> Traceback (most recent call last):
  File "layered_planner.py", line 14, in <module>
    from swarmlib import Drone, Obstacle
ImportError: cannot import name 'Drone' from 'swarmlib' (/usr/local/lib/python3.7/dist-packages/swarmlib/__init__.py)

I have looked into swarmlib functions and all I could find was 
Firefly Algorithm
Cuckoo Search
Particle Swarm Optimization
Ant Colony Optimization

There was no Drone or Obstacle in it as shown by your code

`from swarmlib import Drone, Obstacle`

Kindly a reply back would be helpful.
Thanks

**Comment by rlnav** [comment]
I apologize, I forgot to include the file:
https://github.com/RuslanAgishev/adaptive_swarm/blob/master/scripts/swarmlib.py
